name: Publish

permissions:
  contents: write
  deployments: write
  issues: read
  pull-requests: write

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npx semantic-release
